version: "3.9"


networks:
    app-tier:
      driver: bridge
services:

  comite_container:
    image: comite-api
    container_name: comite_container
    ports:
      - "5050:5050"
    env_file:
      - ./.env
   
      
    volumes: 
      - /media/chris/linux/Docuemtos/menita/agricactus/agc-api:/usr/src/agricactus-api
        # - "./src/configs/firebase/comite-firebase-adminsdk-az0yy-cc97ff94cb.json:/node/app/comite-firebase-adminsdk-az0yy-cc97ff94cb.json"
    depends_on: 
      - mysql
    networks:
      - app-tier
    # networks:
    #   - comite-api_comite_network

  mysql:
      image: mysql:8.0.33
      volumes:
          - /media/chris/linux/DB/mysql-data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 123456
      networks:
        - app-tier      

  # comite_redis:
  #   image: redis:7.0.5
  #   container_name: comite_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - comite-api_comite_network

# networks:
#   comite-api_comite_network:
#     external: true
